language: node_js
node_js:
- '8'
before_install:
- npm install -g greenkeeper-lockfile
install:
- npm install
before_script: greenkeeper-lockfile-update
script:
- npm run lint
after_script: greenkeeper-lockfile-upload
notifications:
  slack:
    secure: QiB918+G3hHGYT2Qw5MfN9gDh+V2Zj6perenormZNC1uD5RmkpqfUitHdbXvseUnGmgN2G0M05j6jSpDQf21BkJX+/x92io6Zm0Dzvx5dXNC39cJFGaEhJmPjhYstbpnadysji2qQ7E+UMo7MewnlFMfuQQOywH11RBgpCBYy0ZCy/8VkN2xV15RAI1ISNBQHZ+z8F05wk+J1OOftQpBtyjZRuhbF3efwZmpRA8lyVoMPuCppZ0JfDGHewKbNqtBIC2zDjS3UgOpKLm7Y5yQ1m8epS+N1E3m8SI2pkYbZvURTKlD0Ip0FAqzAf+UOAgePzYmHH88qYPd6M3NM6JdnveLF3w58VWLriFYbIuffyW6iJHnp2APXy0lsBAd4ezFnviucrKHFfGC17he38dIovos/xBZlTHOGfaKmRwHxnS3ZK80KjGRc0Fivq9pjHWu67qXDLeKQLB/Rm3h5dozPdUVWzdq/bj224AYLlJAVb4Q4l/InLRedJpvZWW6rblsLo/JgePK/IP9tzKSvamUxvt9luWoxVgPn0toR8fJ5hxVZL5hmeZslgsD76olayNnQbvf6zRhi7n71S22sKJVwazfxg3UTHRMllRmOmB3czjhmCQRMab3Ez9aO9JKfAznwkV5IcLTB7VXFVeFMl53EUh6+tnNtzaE1DkMd62N33k=
env:
  global:
    secure: AGWubAFyT7zHZq+zhSWd4SuyZoa6iqLT8Idrm/vvB7PyKU+nT64sUnZEdrLDDxtS4CeUuGATMn58UHCYehSPsl6sx4d7Eow8+XZizhEjhUa1LWhgQMkhsubkrPxB6h0koxZ/QMV7/JXZ5jnBxrd9dn651oobEiQNyvGKMtU2xCbHbgGKI8rld5BUhG10IFz3H6RaKKhEiGe5Raz38ALgeS669OreiDyaBQBNeis1vechdkgq1bOwGyVZiWwL2EdH+0Fx9heEd+pfR2BWa3MLATBIYyg0+OGwLEMX5ireOOIfwwDnoq5KbqoQp3KEx5yQqp5LFcIJNGw9zUnCZGDGoLCs5iuthQABvfsgY/mEsRkJeEiEVHxA05T0+3PCDy8/leqy2KIgP7UzkCe8iRrTK3cEY3eq++veqijBHRxogHvMzfpP186fjcIWxO6EIrR+8RNGgRVAz51OMyuseWZYzftlXozFS5xkQwRmHZZTq2hWTKEpiejW58VQkpMhkdWZNPzNTs2FGyH4Ia1ZA+8vadcFz8qh7pJM1/9f2xtZ5hJALUHXfIpgGMwMnFPJTF0WvlXdwsgcywHPL7s+Ip0Z8pOBzku5RFGjxGtklab28EF4NWOpBBkws+KgYrbtELfZLS5uXVTl8/wvP9lH/14gIFlceLCMI6U740XBOP/LOQI=
